// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yguvxzxvjopsxmbyxepa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndXZ4enh2am9wc3htYnl4ZXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjEwMjcsImV4cCI6MjA2NDUzNzAyN30.rA5YZdd7aptVZnYG1H2omhL_TQhS326yncq_JIKJ_7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);